### ISSUE TITLE
Command 'esmcaption' raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access

### ISSUE THREAD

**Issue by telaphone99** [reticivis-net/mediaforge#242]
### Describe the bug

it does not work.

### Traceback

DATETIME:2024-05-02 12:53:32.824463
COMMAND:/esmcaption {'caption': 'test caption'}
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 175, in esmcaption
    await process(ctx, processing.vips.vipsutils.generic_caption_stack, [["VIDEO", "GIF", "IMAGE"]],
  File "/mediaforge/src/core/process.py", line 151, in process
    raise e
  File "/mediaforge/src/core/process.py", line 62, in process
    urls = await imagesearch(ctx, len(inputs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/utils/scandiscord.py", line 82, in imagesearch
    async for m in ctx.channel.history(limit=50, before=ctx.message):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/abc.py", line 1804, in history
    data, state, limit = await strategy(retrieve, state, limit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/abc.py", line 1746, in _before_strategy
    data = await self._state.http.logs_from(channel.id, retrieve, before=before_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'esmcaption' raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access

### Expected Behavior

it to work.

### Steps To Reproduce

1. send an image
2. do /esmcaption
3. it breaks

**Comment by telaphone99** [comment]
okay for some reason this only happens in private channels

**Comment by reticivis-net** [comment]
> okay for some reason this only happens in private channels

this is because mediaforge doesn't have access to the channel to scan for messages. it needs read message AND message history perms.
